### ISSUE TITLE
error Nothing responds to "realClick"

### ISSUE THREAD

**Issue by jelenajjo** [Mr0grog/nightmare-real-mouse#11]
I just installed your plugin, but can't make it work. I get the _**error Nothing responds to "realClick"**_ . The click selector is correct, I tested it with nightmare default `.click()` so that is not what is issue.

I also get same error when I test your example script:

```
const Nightmare = require('nightmare');
const nightmare = Nightmare({ show: true })
const realMouse = require('nightmare-real-mouse');

// add the plugin
realMouse(Nightmare);

nightmare
  .goto('http://yahoo.com')
  .type('form[action*="/search"] [name=p]', 'github nightmare')
  // use realClick() instead of click()
  .realClick('form[action*="/search"] [type=submit]')
  .wait('#main')
  .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

Any idea what is causing it?

**Comment by rosshinkley** [comment]
You're including the plugin (which modifies the Nightmare prototype) _after_ the instance is created.  This means that the instance won't include the mechanics to handle the call to `.realClick()`.

Try moving the instantiation to after `realMouse(nightmare)`, you'll have better results.

**Comment by jelenajjo** [comment]
@rosshinkley  Yep, that solved issue! :) :+1:
