### ISSUE TITLE
Enable user to specify location of mouse event?

### ISSUE THREAD

**Issue by Zzzen** [Mr0grog/nightmare-real-mouse#31]
Because I'm writing a pixijs app...

```
nightmare
  .goto('http://yahoo.com')
  .realClick('form[action*="/search"] [type=submit]', { x: 2, y: 2 })
```

**Comment by Zzzen** [comment]
fix typo

**Comment by Mr0grog** [comment]
Hi @Zzzen, I probably won’t have any time to work on this until much later this week, but if you want to take a stab at it, you’d just need to change the implementation (and maybe the name) of `actionOnElementCenter` here: https://github.com/Mr0grog/nightmare-real-mouse/blob/master/index.js#L96-L105 (plus add some tests)

**Comment by Zzzen** [comment]
What do you think about it

**Comment by Zzzen** [comment]
Hello? @Mr0grog

**Comment by Mr0grog** [comment]
Sorry it’s taken me some time to get back to this. It might be a good idea to validate the input `position` the same way we do the `selector`. Otherwise, looks good! Are you going to submit a PR?

**Comment by Zzzen** [comment]
Make sure that the input `position` is in boundingClientRect of `selector`? And yes, I want to submit a PR.

**Comment by Mr0grog** [comment]
> Make sure that the input `position` is in boundingClientRect of `selector`?

Oh, I was just thinking that it has `x` and `y` properties that are numbers! But we could definitely also check that it’s in-bounds.

> And yes, I want to submit a PR.

Great, I’ll look forward to it 👍
