### ISSUE TITLE
Nightmare 3.0.0

### ISSUE THREAD

**Issue by xeBuz** [Mr0grog/nightmare-real-mouse#34]
Hello! 
Nightmare was released few hours ago. Is this plugin compatible with the new version?

I'm having a dependency issue:
```
npm WARN nightmare-real-mouse@1.0.0 requires a peer of nightmare@^2.4.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by Mr0grog** [comment]
Given that 3.0 is about a change that probably breaks all plugins (https://github.com/segmentio/nightmare/pull/1391), almost certainly not. I probably won’t have any time to get to this soon, but if you want to work on it, I’ll happily review a PR.
