### ISSUE TITLE
realClick() not working

### ISSUE THREAD

**Issue by alexisghillis** [Mr0grog/nightmare-real-mouse#39]
Hi,
I am using codeceptjs with nightmarejs. 
When running the test I use:

```
 const weNeed = require('nightmare');
require('nightmare-real-mouse')(weNeed);
```
Inside the test is this call:
```
I.clickForReal('selector')
```
where:
``` 
clickForReal(what) {
        let browser = this.helpers['Nightmare'].browser;
        browser.realClick(what);
    }
```
I tested the selectors and they work, unfortunately the realClick() method does nothing. Tried it with simple elements (no react selectors). 
1 year ago I know it worked, now it does not.
Any ideas?

I am working with:
```
"dependencies": {
    "chai": "^4.1.2",
    "codeceptjs": "^2.0.1",
    "express": "^4.16.4",
    "nightmare": "^3.0.1",
    "nightmare-real-mouse": "^1.1.0",
    "superagent": "^3.8.3"
  }
```

**Comment by alexisghillis** [comment]
Well it works :)
I forgot to place a `return":
```
clickForReal(what) {
        let browser = this.helpers['Nightmare'].browser;
        return browser.realClick(what);
    }
```

**Comment by Mr0grog** [comment]
Sorry I’ve been away for the past couple weeks, but it looks like you got it worked out on your own! I’ll close this, but just post back here again if I’m missing something that actually needs fixing in this package :)
