### ISSUE TITLE
Project still Active ? :)

### ISSUE THREAD

**Issue by johnnash999** [Mr0grog/nightmare-real-mouse#45]
Is this Project still Active ? :)

**Comment by Mr0grog** [comment]
I’m happy to accept pull requests for bug fixes, but otherwise I wouldn’t say this project is particularly active. It’s been fairly feature-complete for a while, and Nightmare itself hasn’t had a single new commit to its master branch in more than a year.

Were you after anything in particular?

**Comment by Mr0grog** [comment]
(FWIW, I don’t actually have any use-cases for this or Nightmare in my own work these days, since most of what I used to use it for is better done with Puppeteer or Spectron now.)

**Comment by johnnash999** [comment]
Sir, is there anyway to Hire you for 1 - 3 hours of consultation ? are you available on upwork or freelancer  ? :)
